CREATE TABLE CLIENTES(
ID_CLIENTE INTEGER NOT NULL AUTOINCREMENT,
NOME VARCHAR(150),
DT_NASCIMENTO DATE,
CPF VARCHAR(10),
ENDERECO VARCHAR(150),
PRIMARY KEY (ID_CLIENTE)
)

CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO INTEGER NOT NULL ,
NOME VARCHAR(150),
CPF VARCHAR(10),
TIPO CHAR(1),
DT_NASCIMENTO DATE,
PRIMARY KEY (ID_FUNCIONARIO)
)

CREATE TABLE FORMA_PAGAMENTOS(
ID_PAGAMENTO INTEGER NOT NULL,
NOME VARCHAR(150),
PRIMARY KEY(ID_PAGAMENTO)
)


CREATE TABLE VENDAS(
ID_VENDA INTEGER NOT NULL ,
ID_CLIENTE INTEGER NOT NULL,
ID_FUNCIONARIO INTEGER NOT NULL,
ID_FORMAPGTO INTEGER NOT NULL,
VL_TOTAL DOUBLE,
DESCONTO DOUBLE,
PRIMARY KEY (ID_VENDA),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
)

CREATE TABLE VENDAS_ITENS(
ID_VENDA INTEGER,
ID_PRODUTO INTEGER,
VL_PRODUTO DOUBLE,
QTDE_PRODUTO INTEGER,
PRIMARY KEY(ID_VENDA,ID_PRODUTO),
FOREIGN KEY(ID_VENDA) REFERENCES VENDAS(ID_VENDA),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
)

